// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateMD5(arg1) {
  return window['go']['main']['App']['CalculateMD5'](arg1);
}

export function ClearWebDAVLogs() {
  return window['go']['main']['App']['ClearWebDAVLogs']();
}

export function CopyFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2, arg3);
}

export function CreateShelf(arg1) {
  return window['go']['main']['App']['CreateShelf'](arg1);
}

export function DeleteBook(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteBook'](arg1, arg2, arg3);
}

export function DeleteDirectory(arg1) {
  return window['go']['main']['App']['DeleteDirectory'](arg1);
}

export function DeleteShelf(arg1) {
  return window['go']['main']['App']['DeleteShelf'](arg1);
}

export function DownloadShelf(arg1) {
  return window['go']['main']['App']['DownloadShelf'](arg1);
}

export function DownloadSingleEpub(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadSingleEpub'](arg1, arg2, arg3);
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function GetBooksDir() {
  return window['go']['main']['App']['GetBooksDir']();
}

export function GetFileBytes(arg1) {
  return window['go']['main']['App']['GetFileBytes'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetProgress(arg1) {
  return window['go']['main']['App']['GetProgress'](arg1);
}

export function GetShelfDir() {
  return window['go']['main']['App']['GetShelfDir']();
}

export function GetWebDAVLogs() {
  return window['go']['main']['App']['GetWebDAVLogs']();
}

export function LoadShelfData(arg1) {
  return window['go']['main']['App']['LoadShelfData'](arg1);
}

export function LoadWebDavConfig(arg1) {
  return window['go']['main']['App']['LoadWebDavConfig'](arg1);
}

export function OpenConfigDir() {
  return window['go']['main']['App']['OpenConfigDir']();
}

export function OpenFileLocation(arg1) {
  return window['go']['main']['App']['OpenFileLocation'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RenameShelf(arg1, arg2) {
  return window['go']['main']['App']['RenameShelf'](arg1, arg2);
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3);
}

export function SaveProgress(arg1, arg2) {
  return window['go']['main']['App']['SaveProgress'](arg1, arg2);
}

export function SaveShelfData(arg1, arg2) {
  return window['go']['main']['App']['SaveShelfData'](arg1, arg2);
}

export function SaveShelfOrder(arg1) {
  return window['go']['main']['App']['SaveShelfOrder'](arg1);
}

export function SaveWebDavConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveWebDavConfig'](arg1, arg2);
}

export function ScanEpubFilesInFolder(arg1) {
  return window['go']['main']['App']['ScanEpubFilesInFolder'](arg1);
}

export function ScanShelves() {
  return window['go']['main']['App']['ScanShelves']();
}

export function SelectEpubFiles() {
  return window['go']['main']['App']['SelectEpubFiles']();
}

export function SelectEpubFolder() {
  return window['go']['main']['App']['SelectEpubFolder']();
}

export function SelectMultipleEpubFiles() {
  return window['go']['main']['App']['SelectMultipleEpubFiles']();
}

export function SyncBookConfig(arg1) {
  return window['go']['main']['App']['SyncBookConfig'](arg1);
}

export function SyncLibrary(arg1) {
  return window['go']['main']['App']['SyncLibrary'](arg1);
}

export function SyncShelf(arg1) {
  return window['go']['main']['App']['SyncShelf'](arg1);
}

export function TestShelfWebDav(arg1) {
  return window['go']['main']['App']['TestShelfWebDav'](arg1);
}

export function TriggerAutoSync(arg1) {
  return window['go']['main']['App']['TriggerAutoSync'](arg1);
}

export function UploadShelf(arg1) {
  return window['go']['main']['App']['UploadShelf'](arg1);
}
