// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {webdav} from '../models';
import {book} from '../models';

export function CalculateFileMD5(arg1:string):Promise<string>;

export function CalculateMD5(arg1:Array<number>):Promise<string>;

export function ClearWebDAVLogs():Promise<void>;

export function CopyFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CopyImageToClipboard(arg1:string):Promise<void>;

export function CreateShelf(arg1:string):Promise<void>;

export function DeleteBook(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteDirectory(arg1:string):Promise<void>;

export function DeleteShelf(arg1:string):Promise<void>;

export function DownloadShelf(arg1:string):Promise<string>;

export function DownloadSingleEpub(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FileExists(arg1:string):Promise<boolean>;

export function ForceQuit():Promise<void>;

export function GetBookLocalPath(arg1:string,arg2:string):Promise<string>;

export function GetBooksDir():Promise<string>;

export function GetEpubImageByPath(arg1:string,arg2:string):Promise<Array<number>>;

export function GetFileBytes(arg1:string):Promise<Array<number>>;

export function GetFileInfo(arg1:string):Promise<main.FileInfo>;

export function GetPendingEpubPath():Promise<string>;

export function GetProgress(arg1:string):Promise<string>;

export function GetShelfDir():Promise<string>;

export function GetWebDAVLogs():Promise<Array<webdav.LogEntry>>;

export function LoadShelfData(arg1:string):Promise<string>;

export function LoadWebDavConfig(arg1:string):Promise<string>;

export function OpenConfigDir():Promise<void>;

export function OpenFileLocation(arg1:string):Promise<void>;

export function ProcessAndImportEpub(arg1:string,arg2:string):Promise<book.ImportResult>;

export function ReadFile(arg1:string):Promise<string>;

export function RegisterEpubTab(arg1:string,arg2:string):Promise<void>;

export function RenameShelf(arg1:string,arg2:string):Promise<void>;

export function SaveBookCover(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string,arg3:Array<number>):Promise<string>;

export function SaveProgress(arg1:string,arg2:string):Promise<void>;

export function SaveShelfData(arg1:string,arg2:string):Promise<void>;

export function SaveShelfOrder(arg1:Array<string>):Promise<void>;

export function SaveWebDavConfig(arg1:string,arg2:string):Promise<void>;

export function ScanEpubFilesInFolder(arg1:string):Promise<Array<string>>;

export function ScanShelves():Promise<string>;

export function SelectEpubFiles():Promise<string>;

export function SelectEpubFolder():Promise<string>;

export function SelectMultipleEpubFiles():Promise<Array<string>>;

export function SyncBookConfig(arg1:string):Promise<void>;

export function SyncLibrary(arg1:string):Promise<void>;

export function SyncShelf(arg1:string):Promise<string>;

export function TestShelfWebDav(arg1:string):Promise<string>;

export function TriggerAutoSync(arg1:string):Promise<void>;

export function UnregisterEpubTab(arg1:string):Promise<void>;

export function UploadShelf(arg1:string):Promise<string>;
